#!/bin/bash
# SPDX-License-Identifier: GPL-3.0-only
# Copyright 2022, Mattias Bengtsson <mattias.jc.bengtsson@gmail.com>

# Dynamic dispatch in the task function.
# shellcheck disable=SC2329

set -euo pipefail

NAUTILUS_SCRIPTS="${XDG_DATA_HOME:-${HOME}/.local/share}/nautilus/scripts/"

NAUTILUS_SCRIPT="${NAUTILUS_SCRIPTS}/.image-convert"
NAUTILUS_SCRIPT_SYMLINKS=( "Image - Add Border" )

################################################################################

# shellcheck disable=SC2329
function debug {
    if [ -v DEBUG ]; then
        echo "${FUNCNAME[1]:+${FUNCNAME[1]}: }${*}" >/dev/stderr
    fi
}

function nautilus-script {
    test -v NAUTILUS_SCRIPT_CURRENT_URI || test -v FORCE_GRAPHICAL
}

function anykey {
    local verb

    verb="${1:-exit}"

    echo
    read -n 1 -srp "Press any key to ${verb}."
    echo
    echo
}

function confirm {
    local default

    default="${1}"

    case "${default}" in
        y) read -p "${*:2} [Y/n] " -n 1 -r -s ;;
        n) read -p "${*:2} [N/y] " -n 1 -r -s ;;
        *) echo "Unknown default value: '${default}'" >&2
           return 2
           ;;
    esac

    echo
    [[ ${REPLY:-${default}} =~ ^[Yy]$ ]]
}

# Print [n/m] with proper alignment
#  n-of-m 1 10    ⇒  [01/10]
#  n-of-m 10 200  ⇒  [010/200]
function n-of-m {
    local n m fmt

    n="${1}"
    m="${2}"
    fmt="%0${#m}d"

    # shellcheck disable=SC2059
    printf "[${fmt}/${fmt}]" "${n}" "${m}"
}

function color {
    local color

    color="${1}"

    case "${color}" in
        b|black)   tput setaf 0 ;;
        r|red)     tput setaf 1 ;;
        g|green)   tput setaf 2 ;;
        y|yellow)  tput setaf 3 ;;
        u|blue)    tput setaf 4 ;;
        m|magenta) tput setaf 5 ;;
        c|cyan)    tput setaf 6 ;;
        w|white)   tput setaf 7 ;;
        *)         echo "ERROR: No such color ${color}!" >&2
                   return 2     ;;
    esac
    shift

    echo "${@}"

    tput sgr0
}
function task {
    local msg out
    local -a cmd

    msg="${1}"
    cmd=("${@:2}")

    printf "%-30s" "${msg} ... "

    if out="$("${cmd[@]}" 2>&1)"; then
        echo -e "[ $(color g -n ✓) ]"
    else
        echo -e "[ $(color r -n ×) ]"
        echo "${out}" | pr -to 6 >&2
        return 1
    fi
}

function isnum {
    case "${*}" in
        ''|*[!0-9]*)
            return 1
            ;;
        *)  ;;
    esac
}

function info {
    echo -e "${*}"

    anykey continue
}

function error {
    local title
    local -a body

    title="${1}"
    body=( "${@:2}" )

    echo "Error: ${title}" >&2

    if [ "${#body[@]}" -gt 0 ]; then
        echo
        for msg in "${body[@]}"; do
            echo "${msg}" >&2
        done
    fi

    exit 2
}

function output-dir {
    if [ -e ./out ]; then
        error "Output directory exists!" \
              "Remove the [out/] directory before trying again!"
    fi

    command install -d out
}

################################################################################

function get-border-width {
    read -p "Border width in pixels: " -r -i 5
    echo

    if ! isnum "${REPLY}"; then
        error "Not a number: '${REPLY}'"
    fi

    echo "${REPLY}"
}

function get-border-color {
    echo "#000000"
}

function add-border {
    local image

    image="${1:-}"

    if [ ! -f "${image}" ]; then
        error "Not an image: '${image}'!"
    fi

    image="$(basename "${image}")"

    convert -bordercolor "${color}" -border "${width}" "${image}"              \
            -quality '100%' "out/${image}"
}

function add-border-main {
    local width color image i tot fmt
    local -a images

    output-dir
    echo

    width="$(get-border-width)"
    color="$(get-border-color)"
    images=( "${@}" )

    echo

    i=0
    tot="${#images[@]}"
    for image in "${images[@]}"; do
        : "$((i++))"
        task "$(n-of-m "${i}" "${tot}") ${image}" add-border "${image}"
    done
}

################################################################################

function install-main {
    if [ ! -e "${NAUTILUS_SCRIPT}" ]; then
        if confirm y "Do you want to install image-convert?"; then
            echo
            task "  Installing image-convert" do-install
        fi
    else
        echo "image-convert is already installed."
        echo
        if confirm y "Do you want to *uninstall* instead?"; then
            echo
            task "  Uninstall image-convert" do-uninstall
        fi
    fi

    exit
}

function do-install {
    command install -DT "${0}" "${NAUTILUS_SCRIPT}"

    pushd "${NAUTILUS_SCRIPTS}" >/dev/null
    for symlink in "${NAUTILUS_SCRIPT_SYMLINKS[@]}"; do
        ln -s ./.image-convert "${symlink}"
    done
    popd >/dev/null
}

function do-uninstall {
    if [ ! -e "${NAUTILUS_SCRIPT}" ]; then
        error "Nothing to do!" "Not installed!"
    fi

    rm "${NAUTILUS_SCRIPT}"

    pushd "${NAUTILUS_SCRIPTS}" >/dev/null
    for symlink in "${NAUTILUS_SCRIPT_SYMLINKS[@]}"; do
        rm "${symlink}"
    done
    popd >/dev/null
}

################################################################################

function main {
    local cmd

    if [ ! -t 0 ]; then
        exec ptyxis --new-window -x "'${0}'$(printf " '%s'" "${@}")"
    fi

    trap anykey EXIT

    cmd="$(basename "${0}")"

    case "${cmd}" in
        "Image - Add Border")    add-border-main "${@}"                       ;;
        image-convert-installer) install-main                                 ;;
        *) error "Internal error!" \
                 "The cmd variable had an unexpected value: '${cmd}'!"
           ;;
    esac
}

main "${@}"; exit
